import {useState} from 'react';
import {Download,Upload,Pencil,Trash2,FileText,X,Save} from 'lucide-react';
import {api,type ManagedTask,type TaskFile} from '../api';
export function TaskDocuments({task,canManage,canSubmit,onSaved,notify,confirm}:{task:ManagedTask;canManage:boolean;canSubmit:boolean;onSaved:()=>Promise<void>;notify:(message:string)=>void;confirm:(message:string,action:()=>Promise<void>)=>void}) {
 const [editing,setEditing]=useState<string|null>(null);const [name,setName]=useState('');const [category,setCategory]=useState('task');const [replacement,setReplacement]=useState<File>();const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 const locked=task.status==='done';
 async function perform(action:()=>Promise<unknown>,message:string){setBusy(true);setError('');try{await action();setEditing(null);setReplacement(undefined);await onSaved();notify(message);}catch(error){setError(error instanceof Error?error.message:'Document action failed.');}finally{setBusy(false);}}
 const groups=[{id:'task',title:'Task documents',description:'The brief, requirements and task instructions.'},{id:'reference',title:'Reference documents',description:'Drawings and supporting reference material.'},{id:'completion',title:'Completion documents',description:'Deliverables and evidence of finished work.'},{id:'legacy',title:'Earlier attachments',description:'Managers can categorize these existing files.'}] as const;
 return <section aria-label="Task documents"><div className="task-document-groups">{groups.map(group=>{
 const files=task.files.filter(file=>(file.category??'legacy')===group.id);if(group.id==='legacy'&&!files.length)return null;
 return <section className="task-document-group" key={group.id}><header><strong>{group.title}</strong><span>{files.length}</span></header><p>{group.description}</p><div className="document-list">{files.map(file=><article className="document-row" key={file.id}>
 <FileText size={18}/><div className="document-info"><strong title={file.name}>{file.name}</strong><small>{file.uploadedBy} / {Math.ceil(file.size/1024)} KB</small></div><button className="icon-button" type="button" title="Download" aria-label={`Download ${file.name}`} onClick={()=>void api.downloadFile(file).catch(error=>setError(error.message))}><Download size={15}/></button>
 {canManage&&!locked?<><button className="icon-button" disabled={busy} type="button" aria-label={`Edit ${file.name}`} onClick={()=>{setEditing(file.id);setName(file.name);setCategory(file.category??'legacy');setReplacement(undefined);}}><Pencil size={14}/></button><button className="icon-button danger" disabled={busy} type="button" aria-label={`Delete ${file.name}`} onClick={()=>confirm(`Delete document "${file.name}"?`,()=>perform(()=>api.deleteDocument(file.id),'Document deleted.'))}><Trash2 size={14}/></button></>:null}
 {editing===file.id?<div className="document-editor"><label>Document name<input maxLength={180} value={name} onChange={event=>setName(event.target.value)}/></label><label>Section<select value={category} onChange={event=>setCategory(event.target.value)}>{groups.map(item=><option key={item.id} value={item.id}>{item.title}</option>)}</select></label><label>Replace file (optional)<input type="file" onChange={event=>setReplacement(event.target.files?.[0])}/></label><div className="row-actions"><button className="ghost-button" type="button" onClick={()=>setEditing(null)}><X size={14}/>Cancel</button><button className="primary-button" disabled={busy||!name.trim()} type="button" onClick={()=>void perform(()=>api.updateDocument(file.id,name,category,replacement),'Document updated.')}><Save size={14}/>Save document</button></div></div>:null}
 </article>)}</div>{!files.length?<small className="document-empty">No documents yet</small>:null}
 {!locked&&group.id!=='legacy'&&(canManage||(group.id==='completion'&&canSubmit))?<label className="file-upload document-upload"><Upload size={14}/>Upload<input disabled={busy} multiple type="file" aria-label={`Upload ${group.title.toLowerCase()}`} onChange={event=>{const files=Array.from(event.target.files??[]);event.target.value='';if(files.length)void perform(()=>api.addFiles(task.id,files,group.id),'Documents uploaded.');}}/></label>:null}
 </section>;
 })}</div>{error?<p role="alert" className="error-message">{error}</p>:null}</section>;
}
