# Netscape HTTP Cookie File
# https://curl.se/docs/http-cookies.html
# This file was generated by libcurl! Edit at your own risk.

#HttpOnly_localhost	FALSE	/	FALSE	1781138137	token	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjlmOWZhNmRlLTJjMjItNDdhNC04YjkwLWI0OTEzY2VhODViZCIsInJvbGUiOiJhcHBsaWNhbnQiLCJzaWQiOiIwZjkxNzdkZi1iNGRkLTRlYzgtOGUxZC0zNzM0MTFmYTlhN2QiLCJpYXQiOjE3ODExMDkzMzcsImV4cCI6MTc4MTEzODEzN30.UNeWFTFMfZCO4Y1rkFlvJy8fJ-lBgWVj6BIuHbAe2-M
