allowBuilds:
  '@prisma/engines': true
  '@prisma/client': true
  argon2: true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true
onlyBuiltDependencies:
  - sharp
  - argon2
  - prisma
  - '@prisma/client'
  - '@prisma/engines'
  - unrs-resolver
  - esbuild
