import "server-only";
import { promises as fs } from "node:fs";
import path from "node:path";
import { randomUUID } from "node:crypto";

/**
 * On-disk storage for uploaded files (transaction documents). Kept OUTSIDE the
 * DB — only metadata lives there. Configurable via UPLOAD_DIR; defaults to
 * ./uploads under the app. Served only through authenticated download routes.
 */
const ROOT = process.env.UPLOAD_DIR || path.join(process.cwd(), "uploads");

export const MAX_UPLOAD_BYTES = 25 * 1024 * 1024; // 25MB

/** Persist a File to <ROOT>/<subdir>/<uuid><ext>; returns the stored filename. */
export async function saveUpload(file: File, subdir: string): Promise<string> {
  const dir = path.join(ROOT, subdir);
  await fs.mkdir(dir, { recursive: true });
  const ext = path.extname(file.name).slice(0, 12).replace(/[^.\w]/g, "");
  const stored = `${randomUUID()}${ext}`;
  const buf = Buffer.from(await file.arrayBuffer());
  await fs.writeFile(path.join(dir, stored), buf);
  return stored;
}

/** Read a stored file back (throws if missing). Filenames are validated to stop
 *  any path traversal — only a bare basename is ever accepted. */
export async function readUpload(subdir: string, stored: string): Promise<Buffer> {
  if (stored.includes("/") || stored.includes("\\") || stored.includes(".."))
    throw new Error("invalid filename");
  return fs.readFile(path.join(ROOT, subdir, stored));
}

/** Write server-generated bytes (e.g. a signed PDF) and return the filename. */
export async function writeGenerated(subdir: string, ext: string, bytes: Buffer): Promise<string> {
  const dir = path.join(ROOT, subdir);
  await fs.mkdir(dir, { recursive: true });
  const stored = `${randomUUID()}${ext}`;
  await fs.writeFile(path.join(dir, stored), bytes);
  return stored;
}
